### ISSUE TITLE
[FEATURE] CONSOLE SPAM

### ISSUE THREAD

**Issue by rawnullbyte** [playit-cloud/playit-minecraft-plugin#27]
Yo, could you please add a new option in config, so you could adjust the log messages, because my console looks like this:
![image](https://github.com/playit-cloud/playit-minecraft-plugin/assets/120054040/7b3ac79e-eb9c-44fa-b77b-a01776558cf7)

and also the send keep alive message is very annoying, I cant view other logs, because the console  is full of them:
![image](https://github.com/playit-cloud/playit-minecraft-plugin/assets/120054040/ae0f70b6-a2c2-4f76-bc09-479d0e7ff04e)

**Comment by rawnullbyte** [comment]
@maxomatic458 @Niravprajapati1 @loriopatrick Pls help

**Comment by maxomatic458** [comment]
this fork has the ability to disable logging https://github.com/uniformization/playit-minecraft-plugin/tree/master

**Comment by rawnullbyte** [comment]
@maxomatic458 Oh, i just edited and recompiled entire plugin 💀
I just commented the lines where it logs to console, there is my recompiled plugin 👍
[playit-minecraft-plugin.zip](https://github.com/playit-cloud/playit-minecraft-plugin/files/13674542/playit-minecraft-plugin.zip)
